aws-observability/aws-otel-dotnet-instrumentation

.github/workflows/application-signals-dotnet-e2e-ec2-asg-test.yml, .github/workflows/application-signals-dotnet-e2e-ec2-canary-test.yml, .github/workflows/application-signals-dotnet-e2e-ec2-default-test.yml
Fix E2E test based on private endpoint
*Test*
https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/10271780404
=> E2E Test Fix on private sample app endpoint

test/build-and-install-distro.sh, test/set-up-contract-tests.sh
Update scripts to create `dist` folder and install required Python dependencies.
=> Fix scripts of contract test

build/Build.cs
=> Bump OTel .NET Auto-instrumentation to v1.7.0

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs
Fixed an issue with Metrics where the `telemetry.distro.*` weren't added correctly to the resource builder. Tested by running in a container with the CWAgent and confirmed that the `Telemetry.SDK: Str(aws-otel-dotnet-instrumentation,1.2.0.dev0-aws,dotnet,Auto)` while previously, it was `Telemetry.SDK": "opentelemetry,1.8.1,dotnet,Manual`
=> Fixed Resources Attributes for Metrics

.github/workflows/main_build.yml, .github/workflows/release_build.yml
Updated the release and main build workflows for uploading scripts
=> Updated the release and main build workflows for uploading scripts

.github/workflows/main_build.yml, .github/workflows/release_build.yml, .github/workflows/unlist_nuget.yml
Release fix for nuget and arm64 typo
=> Release fix for nuget and arm64 typo

.github/workflows/main_build.yml, .github/workflows/release_build.yml, .github/workflows/unlist_nuget.yml
Fixed workflows after latest release
=> Fixed workflows after latest release

Dockerfile.linux, Dockerfile.windows2019, Dockerfile.windows2022
Added license files to docker images
=> Added license files to docker images

.github/workflows/application-signals-e2e-test.yml, .github/workflows/main_build.yml
Add Linux EKS Run in Main Build
=> Add Linux EKS Run in Main Build

.github/workflows/application-signals-e2e-test.yml, .github/workflows/main_build.yml
=> Add Windows EKS Test for Main Build

.github/workflows/application-signals-e2e-test.yml, .github/workflows/main_build.yml
Enable EC2 Windows Test for Release Build
Enable EC2 Windows Test for Release Build
=> Enable EC2 Windows Test for Release Build

.github/workflows/release_build.yml, src/AWS.Distro.OpenTelemetry.AutoInstrumentation/nuget-readme.md
Updated release workflow with changes that were detected as required during the v1.3.2 release. Also updated the Nuget README to provide an example on how to set it up and get it running. 
=> Updated release workflow and Nuget README

src/OpenTelemetry.Instrumentation.AWS/Implementation/AWSTracingPipelineHandler.cs, test/contract-tests/tests/test/amazon/awssdk/awssdk_test.py
Updating `gen_ai.system` attribute key to better align with upstream Otel conventions.
Context: https://github.com/open-telemetry/semantic-conventions/pull/1574#issuecomment-2539951918
*Test plan:*
Ran updated contract tests
=> update gen_ai.system attribute key

.github/workflows/main_build.yml, .github/workflows/release_build.yml, .github/workflows/release_lambda.yml
Cherry picking change from main to v1.6.x release branch
=> Updated upload-artifact action to v4

.github/workflows/application-signals-e2e-test.yml, .github/workflows/release_build.yml, .github/workflows/release_lambda.yml
Cherry picking the download-artifact action PR to the release branch.
=> Updated download-artifact action to v4 and Windows Cluster test name

.github/workflows/release_build.yml, .github/workflows/release_lambda.yml
Same as: https://github.com/aws-observability/aws-otel-python-instrumentation/pull/335 and https://github.com/aws-observability/aws-otel-python-instrumentation/pull/337
=> Update SDK and Lambda Layer Release Workflows to Add layer.zip Artifacts

.github/workflows/application-signals-e2e-test.yml
=> Fix typo in release test to pass in correct instrumentation version

buildtools/sign_files.ps1
Cherrypicking change to fix the nuget build signing script
=> Merge fix nuget build signing script from main

sample-applications/lambda-test-apps/SimpleLambdaFunction/README.md
=> Updated Lambda Layer README

.github/workflows/daily_scan.yml, .github/workflows/post_release_version_bump.yml
Updated daily scan workflow to use v1.7.0 ECR image and also updated the post release workflow to auto update those versions in the daily scan workflow. 
Testing:
Tested locally by running the `sed` command and it updated the version in the daily_scan.yml file as expected. 
=> Updated daily scan to use v1.7.0 ECR image

.github/workflows/release_lambda.yml
Same as: https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1096
=> adding release safety via environment

.github/workflows/main_build.yml, .github/workflows/release-lambda.yml, .github/workflows/release_lambda.yml
Cherry-picking bug fix changes from main
=> Fix release workflow

.github/workflows/release-lambda.yml
Follow up from https://github.com/aws-observability/aws-otel-dotnet-instrumentation/pull/226/files
Applying the fix to this branch as well
=> Remove extra regions

.github/workflows/release-build.yml, Dockerfile.windows2019
Cherry pick PR #250 from release/v1.9.x. branch to main.
=> Stop Creating Retired Windows 2019 Image (#250)
