src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsMetricAttributeGenerator.cs
test/AWS.Distro.OpenTelemetry.AutoInstrumentation.Tests/AwsMetricAttributesGeneratorTest.cs

*Description of changes:* Call `EscapeDelimiters()` on remote resource identifiers to ensure special characters are properly escaped.

Fix remote resource value handling with special chars

---

.github/workflows/main_build.yml
.github/workflows/release_build.yml

Verified that no additional code changes are required to support arm64 builds. Verified on an arm64 EC2 instance using both the zip file and the NuGet pkg. For NuGet, built it using an x64 mac and then used on an arm64 EC2 instance to verify that NuGet pkg is platform agnostic. 
For the release workflow testing: Tested using a local branch by moving the new release code to the main build and running it against a private ECR repo. The workflow passed and was able to push to private repo.
Pulled the image and verified that it’s an
```
"Architecture": "arm64",
"Os": "linux",
```
using docker image inspect and started a shell using the image and verified the instrumentation folder is there
```
user@88665a24d661 Downloads % docker run -it …
```

Added logic to build and release arm64 images

---

.github/workflows/application-signals-dotnet-e2e-ec2-canary-test.yml
.github/workflows/application-signals-dotnet-e2e-ec2-default-test.yml
.github/workflows/application-signals-dotnet-e2e-ec2-windows-default-test.yml

Implement Windows E2E EC2 Default Test
*Known Limitation & Fixing*
**Terraform cannot obtain status of SSM Document execution so a timer have been place to let the script run**
*Known Issue*
In a small chance, possible for receive remote-service trace before caller-service trace
*Tests*
https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/10515984578

Implementation of Windows E2E EC2 Default Test

---

build/Build.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsSpanProcessingUtil.cs

This PR will fix https://github.com/aws-observability/aws-otel-dotnet-instrumentation/issues/81
Add configuration file of SQL keywords into build and use it to determine SQL command and set aws remote operation.

Add configuration for sql statements in build

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsMetricAttributeGenerator.cs
test/AWS.Distro.OpenTelemetry.AutoInstrumentation.Tests/AwsMetricAttributesGeneratorTest.cs

https://github.com/aws-observability/aws-otel-dotnet-instrumentation/issues/82
Updated logic of parsing the port number so that instead of using casting (`(long)portNumber`), it instead uses the proper conversion function (`Convert.ToInt64(portNumber)`).
*Testing:*
Added unit tests before making the change where the port was either a string or an int32. The tests immediately failed with the same error in the issue above. After making the change in the parsing logic, the tests started passing. 

Fix an issue where GetDbConnection fails if the port is not of type long

---

test/contract-tests/images/applications/TestSimpleApp.AWSSDK.Core/AmazonClientConfigHelper.cs
test/contract-tests/images/applications/TestSimpleApp.AWSSDK.Core/TestSimpleApp.AWSSDK.Core.csproj

Update AWS SDK contract test application to use latest AWS SDK version (4.0.0 - preview), and verify the backward compatibility with current instrumentation library by running the contract tests:
`====== 11 passed in 58.73s ======`

Update AWS SDK contract test application to use latest AWS SDK version

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsSpanProcessingUtil.cs
test/contract-tests/tests/test/amazon/efcore/efcore_test.py
test/contract-tests/tests/test/amazon/netcore/netcore_test.py

updated logic for generating aws.local.operation so that both Server and Consumer have the same operation.

updated logic for generating aws.local.operation

---

.github/workflows/main_build.yml
.github/workflows/post_release_version_bump.yml
.github/workflows/pre_release_prepare.yml
.github/workflows/release_build.yml
README.md
build/Build.InstallationScripts.cs
instrument.sh
sample-applications/integration-test-app/build-and-start-application.sh
script-templates/AWS.Otel.DotNet.Auto.psm1.template
script-templates/aws-otel-dotnet-install.sh.template
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs

Updated the installation script templates so that when we build the application, the scripts are built accordingly. Also updated the templates to use the AWS Otel Distro instead of the upstream Otel Distro. I also updated the README to reflect that we are using DockerFiles for windows images that fall under the [Windows EULA Agreement](https://learn.microsoft.com/en-us/virtualization/windowscontainers/images-eula)
*Testing:*
Tested that the scripts on both linux and windows and made sure they are working as expected. Set the version to 1.2.0 since that's the latest release and ran the script aws-otel-dotnet-install.sh which basically downloads the 1.2.0 from the releases page and unpacks the zip file. Replaced the unpacked contents with …

Added auto instrumentation scripts and updated GH workflow for release

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs

When application signals feature is not enabled, don't wrap AlwaysRecordSampler since it will mark all spans as recorded and introduce performance overhead.

Set sampler directly to remove overhead of AlwaysRecordSampler

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs

Before this change, only metrics had the resource detector attributes setup. Updated the ConfigureResource plugin function to not only set the distro resource attributes but also use the resource detectors. The ConfigureResource function is called by upstream to configure the resource attached to the trace exporter. This also means that these will apply to all spans even if application signals is disabled. 
Below is an example log for an activity from an EC2 instance. 
```
Activity.TraceId:            8cfa5eb16e6cff7885583babf28e5b9b
Activity.SpanId:             7bbbe008cde165b3
Activity.TraceFlags:         Recorded
Activity.ActivitySourceName: OpenTelemetry.Instrumentation.AspNetCore
Activity.ActivitySourceVersion: 1.9.0.42
Activity.DisplayName:        GET …
```

Added resource detectors and attributes for trace instrumentation

---

src/OpenTelemetry.Instrumentation.AWS/OpenTelemetry.Instrumentation.AWS.csproj

It fixed the following error when doing instrumentation for .NET Framework application.
> Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'OpenTelemetry.AutoInstrumentation.Loader.Loader' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileLoadException: Could not load file or assembly 'OpenTelemetry.Instrumentation.AWS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named …

Sign local build of OpenTelemetry.Instrumentation.AWS

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AWS.Distro.OpenTelemetry.AutoInstrumentation.csproj
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs

This new function runs the sampler a second time after the needed attributes (such as UrlPath and HttpTarget) are finally available from the http instrumentation libraries. The sampler hooked into the Opentelemetry SDK runs right before any activity is started so for the purposes of our X-Ray sampler, that isn't going to work and breaks the X-Ray functionality. Running it a second time after http instrumentation libraries are run allows us to retain the sampler functionality.
Below is the stack trace showing the sampler running before the instrumentation libraries are started.
```
at OpenTelemetry.Sampler.AWS.AWSXRayRemoteSampler.ShouldSample(SamplingParameters& samplingParameters) in …
```

Added logic to run sampler a second time after http instrumentation libraries

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs

Fix .NET Framework support of sampling rule like #107 and filter GetSamplingRules/GetSamplingTargets API calls from X-Ray Sampler.

Filter service requests and support sampling rule for X-Ray Sampler in .NET Framework

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsSpanMetricsProcessor.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsSpanMetricsProcessorBuilder.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs
test/AWS.Distro.OpenTelemetry.AutoInstrumentation.Tests/AwsSpanMetricsProcessorTest.cs

Added logic to flush remaining metrics during shutdown from the AwsSpanMetricProcessor. 
*Testing:*
Tested by setting the metric and trace exporting interval to 1 minute. Before the change, shutting down the application before the minute ends only exports the trace to the collector. After the change, both traces and metrics are always exported before application shutdown. 

Added logic to flush remaining metrics during shutdown

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsAttributeKeys.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsBatchUnsampledSpanExportProcessor.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs
test/AWS.Distro.OpenTelemetry.AutoInstrumentation.Tests/AwsBatchUnsampledSpanExportProcessorTest.cs

AwsBatchUnsampledSpanExportProcessor class that functions similar to BatchActivityExportProcessor having the same input parameters and the same default values. However, the difference is that BatchActivityExportProcessor only exports sampled (or recorded) activities while AwsBatchUnsampledSpanExportProcessor sets the AttributeAWSTraceFlagSampled to false if activity is not sampled and exports unsampled spans only. As a result, there are two udp exporters added, one wrapped with `BatchActivityExportProcessor` and signal prefix = `T1S` and the other wrapped with `AwsBatchUnsampledSpanExportProcessor` and sends data with signal prefix = `T1U`
*Testing:*
Tested by adding unit tests to verify that both sampled and unsampled spans are being exported. Also tested by …

Added unsampledSpan processor implementation

---

.github/workflows/application-signals-e2e-test.yml

While working on fixing E2E tests, found that there are cases in EKS tests where the incorrect ECR image SHA is being used. Instead of using the latest one, it's using an older version. In this case, it could be using images which aren't from the latest changes. This change appends the git commit hash at the end so that each image is unique. 
*Tested:*
While running E2E tests, updated the branch temporarily to be part of the main_build workflow. Previously, both linux and windows eks tests were using an older hash. With this change, they are using the correct one. Example run can be found here: https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/11963044474
By submitting this pull request, I confirm that you can use, modify, copy, …

Added git commit SHA to image build for staging

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsMetricAttributeGenerator.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/ScopeBasedOtlpMetricExporter.cs
test/AWS.Distro.OpenTelemetry.AutoInstrumentation.Tests/AwsMetricAttributesGeneratorTest.cs
test/AWS.Distro.OpenTelemetry.AutoInstrumentation.Tests/ScopeBasedOtlpMetricExporterTest.cs

Bootstrap .NET plugin with the ability to collect runtime metrics.

Add Application Signals runtime metrics with feature disabled

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs
test/contract-tests/images/applications/AppSignals.NetCore/Program.cs
test/contract-tests/images/mock-collector/mock_collector_client.py
test/contract-tests/tests/test/amazon/base/contract_test_base.py
test/contract-tests/tests/test/amazon/runtime/runtime_metrics_test.py
test/contract-tests/tests/test/amazon/utils/application_signals_constants.py

Enable runtime metrics collection by default. This PR is a follow-up PR of https://github.com/aws-observability/aws-otel-dotnet-instrumentation/pull/148.

Enable Application Signals runtime metrics

---

.github/workflows/application-signals-e2e-test.yml

Fixed dotnet lambda layer E2E to run against main. This revert was missed before merging the Lambda Layer E2E as I was testing against another branch until the changes were merged to main.

Fixed dotnet lambda layer E2E to run against main.

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AWSXRayEventSource.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AWSXRayPropagator.cs
src/AWS.Distro.OpenTelemetry.AutoInstrumentation/GlobalSuppressions.cs

Added temporary patch for AWSXRayPropagator. This is copied from upstream. After making the changes upstream, the released version is v1.10 while we are currently working with OTEL v1.9. As a result, we can't yet use the updated version from upstream until we upgrade our otel ref to v1.10. As a result, pushing this locally for now until the next update. 

Added temporary patch for AWSXRayPropagator

---

instrument.sh

Updated the instrument.sh script to enable HTTP Instrumentations for Lambda usecase by default. This is required for calls made by API Gateway to another lambda function to appear as a connected graph.
Tested without, the graphs were disconnected. After adding this change, the graphs were connected as expected. 

Enabled HTTP Instrumentations for Lambda usecase

---

instrument.sh

Cherry picking this https://github.com/aws-observability/aws-otel-dotnet-instrumentation/commit/0b17017f7e7fabd419defb8d8fa14a02a49c5fe5 to be released for the lambda layer in v1.6.0

Enabled HTTP Instrumentations for Lambda usecase (#162)

---

.github/workflows/main_build.yml
.github/workflows/release_build.yml
.github/workflows/release_lambda.yml

Builds were automatically failing because we are using v3 of the checkout action. This updates it to v4: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Updated upload-artifact action to v4

---

.github/workflows/application-signals-e2e-test.yml
.github/workflows/release_build.yml
.github/workflows/release_lambda.yml

Follow up to this [PR](https://github.com/aws-observability/aws-otel-dotnet-instrumentation/commit/9c8b40c2241d0b8af4ec5f0bba30a6b13125f25d) but this time updating the download-artifact action to v4. 

Updated download-artifact action to v4

---

.github/workflows/application-signals-e2e-test.yml

Updated the E2E Windows Cluster Name. The cluster name was changed in this PR: https://github.com/aws-observability/aws-application-signals-test-framework/pull/354

Updated the E2E Windows Cluster Name

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/AwsSpanMetricsProcessor.cs
test/AWS.Distro.OpenTelemetry.AutoInstrumentation.Tests/AwsSpanMetricsProcessorTest.cs

ADOT SDK resource detectors by default have enabled a few AWS resource detector which will call EC2 metadata API endpoints. These activities have been captured by auto-instrumentation and generated AppSignals metrics.
Suppress AwsSpanMetricsProcessor from generating metrics when the RemoteService points to 169.254.169.254
*Testing*:
Tested using Java Adot: https://github.com/aws-observability/aws-otel-java-instrumentation/pull/1015

Remove spans with ec2 metadata ip address from metrics

---

.github/workflows/release_build.yml

**Description of changes:**
One-liner to sign the new dll files in the ADOT package. 
- Related changes: https://github.com/aws-observability/aws-otel-dotnet-instrumentation/pull/183
**Test Plan:**
None

feat: Updating Release Build Workflow to Sign UDP Exporter Files

---

.github/workflows/release-udp-exporter.yml
sample-applications/udp-exporter-test-app/Controllers/AppController.cs
sample-applications/udp-exporter-test-app/Controllers/Config.cs
sample-applications/udp-exporter-test-app/Controllers/MetricEmitter.cs
sample-applications/udp-exporter-test-app/Dockerfile
sample-applications/udp-exporter-test-app/Program.cs
sample-applications/udp-exporter-test-app/Properties/launchSettings.json
sample-applications/udp-exporter-test-app/README.md
sample-applications/udp-exporter-test-app/Startup.cs
sample-applications/udp-exporter-test-app/appsettings.Development.json
sample-applications/udp-exporter-test-app/appsettings.json
sample-applications/udp-exporter-test-app/collector-config-local.yml
sample-applications/udp-exporter-test-app/config.yaml
sample-applications/udp-exporter-test-app/docker-compose.yml
sample-applications/udp-exporter-test-app/dotnet-sample-app.csproj

- Setting up release workflow for UDP Exporter with a simple integration test.
- Similar PR: https://github.com/aws-observability/aws-otel-python-instrumentation/pull/333
**Test Plan:**
Manually tested workflow run in feature branch:
https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/13776526492

feat: Set up UDP Exporter Release Workflow

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/OtlpAwsSpanExporter/OtlpAwsSpanExporter.cs

The internal AWS SDK SigV4 signer does not automatically inject the x-amz-security-token header into the request when signing.
This leads to a 403 Forbidden error when users use the SigV4 exporter and use temporary credentials from Amazon STS.
Manually injected the security token header into the outgoing request before making the export.
*Testing*
Manual testing was done by running the DotNet Auto Instrumentation on a sample application hosted on a newly created EC2 instance with sufficient permissions to export to XRay OTLP endpoint without editing the local aws config file and verified that the spans exported were showing up on CW Logs aws/spans.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

[Bug] Fixed SigV4 Signer not Automatically Injecting Security Token Header

---

.github/workflows/release_build.yml

Updated GH release to create a draft instead of publishing it. This was causing issues since part of the workflow is trying to retrieve zip files from the previous latest release. However, without the --draft option, the workflow publishes the new release which is then set as latest causing the workflow to fail when trying to get files from a brand new empty release. 
Caught this issue on the most recent release and pushing a fix in a custom branch fixed the issue. 

Updated GH release to create a draft

---

.github/workflows/pre_release_prepare.yml

GitHub cleans data when processed this way in case of abuse attempts when running workflows. Following other repo as an example: https://github.com/aws-observability/aws-application-signals-test-framework/blob/main/.github/workflows/dotnet-lambda-test.yml#L28

[FIX] Move inputs in pre-release to env vars

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs

We do not want to automatically disable Application Signals if SigV4 is enabled. This PR allows Application Signals to run normally with SigV4.

Decouple SigV4 from Application Signals

---

.github/workflows/main_build.yml
.github/workflows/release_lambda.yml

Lambda Layer release workflow was failing because it couldn't find layer.zip artifact. This is because the workflow step was copied as is from the Java/Python steps. In dotnet, we don't generate a separate layer, we actually use the `aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip` artifact as both the linux distro and the layer are basically the same in dotnet. As a result, added a couple of new steps, one to download the `aws-distro-opentelemetry-dotnet-instrumentation-linux-glibc-x64.zip` artifact and the second to rename that artifact to `layer.zip`.
Already tested that part of the workflow and now that latest run is passing. 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

Lambda Layer release workflow fix

---

exporters/AWS.Distro.OpenTelemetry.Exporter.Xray.Udp/OtlpUdpExporter.cs

Adds logic to handle UDP exporter set up for Lambda environments [similar to Python](https://github.com/aws-observability/aws-otel-python-instrumentation/blob/main/exporters/aws-otel-otlp-udp-exporter/src/amazon/opentelemetry/exporters/otlp/udp/exporter.py#L60-L62).

feat: add lambda env detection logic for udp exporter setup

---

.github/workflows/release-udp-exporter.yml

```
Run $nugetKey = aws secretsmanager get-secret-value --secret-id *** --region us-west-2 --output text --query SecretString | ConvertFrom-Json nuget push .\Deployment\nuget-packages\*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $nugetKey.Key
11ConvertFrom-Json: D:\a\_temp\a7d0dc99-0c8b-4fd5-9a40-c3595b71bd03.ps1:2
12Line |
13 2 | … retString | ConvertFrom-Json nuget push .\Deployment\nuget-packages\* …
14 | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15 | A positional parameter cannot be found that accepts argument 'push'.
16Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
17OSError: [Errno 22] Invalid argument
18Error: Process completed with exit code 1.
```
Fixes a syntax error in workflow file was causing the above …

fix udp publish to nuget release step

---

.github/workflows/release-udp-exporter.yml

An attempt to fix the API key error encountered when trying to publish the UDP Exporter to NuGet.
Since this workflow uses the same credentials as our .NET ADOT SDK release workflow, it was strange why [these errors](https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/14579431706/job/40892706595) were occurring. After comparing the two workflow files ([ADOT SDK release workflow](https://github.com/aws-observability/aws-otel-dotnet-instrumentation/blob/main/.github/workflows/release_build.yml), [UDP Exporter release workflow](https://github.com/aws-observability/aws-otel-dotnet-instrumentation/blob/main/.github/workflows/release-udp-exporter.yml)), I noticed some discrepancies that I corrected with this PR's code changes.
```
Run $nugetKey = aws secretsmanager …
```

fix: udp exporter release api key error

---

test/contract-tests/tests/test/amazon/misc/configuration_test.py
test/contract-tests/tests/test/amazon/misc/resource_attributes_test_base.py
test/contract-tests/tests/test/amazon/misc/service_name_in_env_var_test.py
test/contract-tests/tests/test/amazon/misc/service_name_in_resource_attributes_test.py
test/contract-tests/tests/test/amazon/misc/unknown_service_name_test.py

I observed that we were missing the `misc` tests seen in other repos: https://github.com/aws-observability/aws-otel-python-instrumentation/blob/main/contract-tests/tests/test/amazon/misc/
Files copied over, light modification made to make them work. Note that two tests are not working and will need further analysis: test_xray_id_format & test_service

Add misc contract tests

---

sample-applications/udp-exporter-test-app/dotnet-sample-app.csproj

After merging the latest UDP Exporter changes, the E2E test starting failing https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/14913437640/job/41893186439. Did some debugging locally and turns out the application isn't starting due to dependency conflicts. The OTEL dependencies were upgraded from v1.9 to v1.11 in the UDP exporter. This change updates them in the sample app as well. After making the changes locally, the sample app started as expected and I was able to grab a sample trace from there.  

Updated otel pkg versions for the UDP Sample App

---

.github/workflows/main_build.yml
.github/workflows/release-lambda.yml

The lambda layer release workflow is failing because the environment parameter cannot be used while triggering a reusable workflow. 
Moved the environment parameter to main-build and added input variable to specify the environment type
*Testing*:
Release Environment: https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/15937448883
Dev Environment: https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/15937444155

Move environment parameter to main-build

---

.github/workflows/application-signals-e2e-test.yml

Add new validation workflow:
- This validation is to ensure that all ApplicationSignals e2e test workflows relevant to this repo are actually being used in this repo.
- See: https://github.com/aws-observability/aws-application-signals-test-framework/blob/main/.github/workflows/validate-e2e-tests-are-accounted-for.yml
*Testing:*

[AppSignal E2E Testing] Validate E2E Tests Are Accounted For

---

src/AWS.Distro.OpenTelemetry.AutoInstrumentation/Plugin.cs
test/contract-tests/tests/test/amazon/misc/unknown_service_name_test.py

Previously, there was an issue where the service.name attribute is the resource attributes for Traces and Metrics would be different when the service name is not set in the `OTEL_RESOURCE_ATTRIBUTES` env var. Turns out upstream has fallback logic that sets the service.name attribute to the assembly name if it's not set instead of using `unknown_service`. 
However, since we create our own MeterProvider for application signals, the fallback logic doesn't apply for those resources created outside of the opentelemetry instrumentation pkg. This PR adds this logic locally so that if service.name is empty, it calls the fallback function to get the assembly name or the process name. If either of that fail, then we default to `UnknownService`.
*Testing:*
Enabled …

Updated service.name resource attribute logic in Plugin

---

.github/workflows/application-signals-e2e-test.yml

Add EC2 auto-scaling group test case to the main build workflow.
Verified in the dry-run: https://github.com/aws-observability/aws-otel-dotnet-instrumentation/actions/runs/17566192132

chore: add asg test to the main build workflow

---

.github/workflows/application-signals-e2e-test.yml
.github/workflows/release-build.yml

Removes unintentional `continue-on-error` in `application-signals-e2e-test` and `release-build` workflows

Remove `continue-on-error` in e2e and release workflows

---

.github/actions/build-and-scan-image/action.yml
.github/workflows/main-build.yml
.github/workflows/pr-build.yml
.github/workflows/release-build.yml

Disabling fail fast to ensure we all image scan jobs get run regardless of failure of one image scan.
https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstrategyfail-fast
Note:
We can't move the build step from the release-image job because GitHub Actions jobs run on isolated runners - Docker images built in one job aren't available to another job
We can't add fail-fast: false to the release workflow because we need ALL image scans to pass before any images are published - if any scan fails, the entire release should be blocked.

Ensure all steps in Image Scan runs 

---

.github/workflows/codeql.yml

The default CodeQL configuration does not run for forked PRs, causing PRs to simply get stuck. In this PR I have enabled "Advanced configuration", and made no changes to the templated workflow that was created. This is a 2-way door, we can always go back to default if this proves to be the wrong approach. See https://github.com/aws-observability/aws-otel-python-instrumentation/pull/210

Change CodeQL to advanced
